In [31]:
import sys, os
# sys.path.append(os.pardir) : 부모 디렉터리의 파일을 가져올 수 있도록 설정
# sys.path : 파일을 불러올 때 sys.path에 등록되어있는 경로만 뒤져서 파일을 찾아옴
# append : 리스트를 추가할 때 사용하는 매서드
# os.pardir : 상위 폴더
# cf) os.getcwd() : 현재 작업하고 있는 디렉토리 위치를 보여줌(= pwd)
sys.path.append("./dataset") # 이때, dataset 폴더는 실행하는 py 파일의 경로와 일치해야 한다.
import numpy as np
import pickle
from dataset.mnist import load_mnist
import matplotlib.pylab as plt

In [32]:
# set_printoptions : 파이썬이 행렬을 화면에 출력해줄때 행이 너무길어지면 줄넘김을 해주기 때문에
# linewidth=200 : 200개가 넘기 전에 줄넘김을 하지 말라고 하는 것
# threshold=1000 : 항의 개수가 1000개까지는 ...으로 생략하지말고 다 보여주라는 뜻
# 이렇게 해줘야지 행렬 출력했을 때 모양이 예쁘게 나옴
np.set_printoptions(linewidth=200, threshold=1000)

In [33]:
# x : 이미지, t : label
# train : 훈련용 데이터(60000장,해상도 28x28), test : 테스트용 데이터
# flatten : 옆으로 이어붙이는거(?) True로 하면 줄넘김이 되서
#            행렬에서 5라는 모양이 제대로 안나옴
# normalize : 밝기를 0~1까지로 만들어 주는 것
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=False, normalize=False)

Converting train-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting train-labels-idx1-ubyte.gz to NumPy Array ...
Done
Converting t10k-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting t10k-labels-idx1-ubyte.gz to NumPy Array ...
Done
Creating pickle file ...
Done!


In [50]:
# 사진개수 , 채널(흑백/컬러) , H , W
x_train.shape

(60000, 1, 28, 28)

In [46]:
print(x_train[0])

[[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255 247 127   0   0   0   0]
  [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0]
  [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82  82  56  39   0   0   0   0   0]
  [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 182 247 2

In [47]:
print(t_train[0])

5
